import {
  Heart,
  Brain,
  GraduationCap,
  Smile,
  Wallet,
  Repeat,
  Compass,
  Scale,
  Hammer,
  Sparkles,
  MessageCircle,
  Shield,
  Sprout,
  HandHeart,
  Flame,
  Swords,
  Target,
  Hourglass,
  Clock,
  BookOpen,
  Fence,
  HeartHandshake,
  UserCheck,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  "Physical health": Heart,
  "Mental health": Brain,
  "Intellectual growth": GraduationCap,
  "Emotional regulation": Smile,
  "Financial stability": Wallet,
  "Discipline & habits": Repeat,
  "Purpose & meaning": Compass,
  "Integrity & values": Scale,
  "Skills & mastery": Hammer,
  Spirituality: Sparkles,

  Communication: MessageCircle,
  "Trust & honesty": Shield,
  "Shared values": Sprout,
  "Emotional support": HandHeart,
  Intimacy: Flame,
  "Conflict resolution": Swords,
  "Shared goals": Target,
  Patience: Hourglass,

  "Presence & time": Clock,
  Education: BookOpen,
  Boundaries: Fence,
  "Unconditional love": HeartHandshake,
  "Modeling values": UserCheck,
};
